on:
  workflow_call:
    inputs:
      modrinth-id:
        type: string
        required: true
      curseforge-id:
        type: string
        required: true
      version-type:
        type: string
        required: true
      minecraft-versions:
        type: string
        required: false
    secrets:
      modrinth-token:
        required: true
      curseforge-token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Read mod version
        id: versions
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: gradle.properties
          properties: "mod_version minecraft_version"

      - name: Read changelog
        uses: juliangruber/read-file-action@v1
        id: changelog
        with:
          path: "./changelog/${{ steps.versions.outputs.mod_version }}+${{ steps.versions.outputs.minecraft_version }}.md"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          name: "v${{ steps.versions.outputs.mod_version }} [${{ steps.versions.outputs.minecraft_version }}]"
          version: ${{ steps.versions.outputs.mod_version }}+mc.${{ steps.versions.outputs.minecraft_version }}
          version-type: ${{ inputs.version-type }}

          loaders: fabric quilt
          java: 17

          game-versions: ${{ inputs.minecraft-versions || steps.versions.outputs.minecraft_version }}
          changelog: ${{ steps.changelog.outputs.content }}

          modrinth-token: ${{ secrets.modrinth-token }}
          modrinth-id: ${{ inputs.modrinth-id }}
          modrinth-featured: false

          curseforge-token: ${{ secrets.curseforge-token }}
          curseforge-id: ${{ inputs.curseforge-id }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ steps.versions.outputs.mod_version }}+mc.${{ steps.versions.outputs.minecraft_version }}