name: Publish

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: The changelog
        required: true
        type: string
      version-type:
        description: The type of release
        required: true
        type: choice
        options: ["alpha", "beta", "release"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Fix lines in changelog
        id: changelog
        shell: python
        env:
          THE_INPUT: "${{ inputs.description }}"
        run: |
          import os
          import random
          import string
          
          value = os.getenv("THE_INPUT").replace("\\n", "\n")
          # Random delimiter to avoid escapes
          delimiter = "".join(random.choice(string.ascii_letters + string.digits) for i in range(30))
          
          with open(os.environ["GITHUB_OUTPUT"], "w") as out:
              out.write(f"value<<{delimiter}\n{value}\n{delimiter}")

      - name: Print changelog
        run: "echo \"${{ steps.changelog.outputs.value }}\""

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Read mod version
        id: versions
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: gradle.properties
          properties: "mod_version minecraft_version"

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          name: "v${{ steps.versions.outputs.mod_version }} [${{ steps.versions.outputs.minecraft_version }}]"
          version: ${{ steps.versions.outputs.mod_version }}+mc.${{ steps.versions.outputs.minecraft_version }}
          version-type: ${{ inputs.version-type }}

          loaders: fabric quilt
          java: 17 18

          game-versions: ${{ steps.versions.outputs.minecraft_version }}
          changelog: ${{ steps.changelog.outputs.value }}

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: AhtxbnpG
          modrinth-featured: false

          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-id: 616602

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ steps.versions.outputs.mod_version }}+mc.${{ steps.versions.outputs.minecraft_version }}
